# SILENT MEDIC VET — Conditions knowledge base (v0.2.0, ophthalmic pilot)
# Fields:
#  id   stable slug (linked from kb_human.py `cond` and the Eye decision flow)
#  n    name · a aliases/search terms · sys body system · sp species covered
#  tri  triage: E emergency now | U within 24 h | S book a visit (days) | H home care reasonable
#  up   signs that escalate the triage level
#  zoo  zoonotic (bool) · reg regional note (Texas)
#  what owner-level definition · signs · breeds {species:[...]} · home (owner do) · dont
#  hum  tier-7 human-medicine names (prefix match on kb names)
#  dx   diagnostics (DVM) · tx treatment direction (DVM) · rx KB entry names for Rx links (DVM)
#  spn  species-specific notes · rf call-now signs · refs verified citations (PMID) · see related ids
COND = []
def c(**e): COND.append(e)

EXAM3 = "Ask the clinic for the three basic eye tests: Schirmer tear test (tear production), fluorescein stain (corneal ulcer), and tonometry (eye pressure)."

c(id="corneal-ulcer", n="Corneal ulcer (including indolent / SCCED)", sys="Eye", sp=["dog", "cat", "rabbit", "horse"],
  a=["ulcer", "scratched eye", "corneal abrasion", "SCCED", "indolent ulcer", "boxer ulcer", "melting ulcer", "squinting", "keratitis"],
  tri="U", up="Emergency if you can see a pit or crater, the cornea looks gel-like, milky or bluish, the eye bulges, or there is bleeding.",
  zoo=False, reg="",
  what="A scratch or erosion in the clear front surface of the eye (cornea). Most superficial ulcers heal in about a week once the cause is removed; deep or infected ulcers can perforate within days.",
  signs=["Squinting or holding the eye shut", "Tearing", "Rubbing or pawing at the eye", "Redness", "A cloudy or dull spot on the cornea", "Light sensitivity"],
  breeds={"dog": ["Shih Tzu", "Pug", "Pekingese", "Boston Terrier", "French Bulldog", "Lhasa Apso", "Boxer (indolent ulcers)", "Older dogs of any breed (indolent ulcers)"],
          "cat": ["Persian", "Himalayan", "Any cat with feline herpesvirus"]},
  home=["Prevent rubbing — cone (e-collar) now.", "Gently rinse with sterile saline if there is debris.", "Trim hair that touches the eye.", "See a vet within 24 hours; the same day if the eye is cloudy or the animal is in obvious pain."],
  dont=["No steroid-containing eye drops — they can make an ulcer perforate.", "No leftover drops from another person or pet.", "No skin ointments in the eye."],
  hum=["Fluoroquinolone eye drops", "Triple antibiotic eye ointment", "Steroid or steroid-antibiotic eye drops", "Atropine 1%", "Artificial tears"],
  dx=["Fluorescein stain (depth, loose epithelial edge = indolent)", "Schirmer tear test", "Look for the cause: eyelid/hair disorders, ectopic cilia, foreign body behind the third eyelid, KCS, exposure", "Cytology and culture if stromal, infected, or melting", "Seidel test if perforation is suspected"],
  tx="Superficial: broad-spectrum topical antibiotic q6-8h, atropine for ciliary-spasm pain (if IOP and STT allow), oral NSAID or gabapentin, e-collar; recheck in 3-5 days. Not healed by 7-10 days with a loose epithelial lip = indolent ulcer (SCCED): debridement (cotton swab or diamond burr; grid keratotomy in dogs only — avoid in cats because of sequestrum risk), bandage contact lens. Deep or melting: antibiotic q1-2h, anti-collagenase therapy (autologous serum, EDTA, or doxycycline), same-day ophthalmology referral for grafting.",
  rx=["Meloxicam", "Gabapentin"],
  spn={"cat": "Most feline ulcers are herpesvirus-driven — add antiviral therapy. Avoid grid keratotomy.",
       "horse": "Every painful equine eye is an emergency: ulcers can become fungal within days. Needs cytology/culture; never topical steroids.",
       "rabbit": "Look for dental disease and tear-duct infection as underlying causes."},
  rf=["A visible pit, crater, or bulge on the eye", "Cornea turning milky, bluish, or gel-like", "Blood in the eye", "No improvement after 48 hours of treatment"],
  refs=["Gosling AA, Labelle AL, Breaux CB. Management of spontaneous chronic corneal epithelial defects (SCCEDs) in dogs with diamond burr debridement and placement of a bandage contact lens. Vet Ophthalmol. 2013;16(2):83-88. PMID 22520040"],
  see=["kcs", "eyelid-hair", "fhv1", "glaucoma"])

c(id="kcs", n="Dry eye (keratoconjunctivitis sicca, KCS)", sys="Eye", sp=["dog", "cat"],
  a=["dry eye", "KCS", "keratoconjunctivitis sicca", "goopy eyes", "green discharge", "mucus eye", "recurrent eye infection"],
  tri="S", up="Within 24 hours if the eye becomes painful, cloudy, or squinted — dry eyes ulcerate easily.",
  zoo=False, reg="",
  what="The eye does not make enough of the watery part of tears, usually because the immune system damages the tear glands. It is lifelong but well controlled with daily medication.",
  signs=["Thick yellow-green, sticky discharge", "Dull, dry-looking cornea", "Redness", "'Infections' that improve on antibiotics and keep coming back", "Brown pigment or blood vessels growing across the cornea"],
  breeds={"dog": ["West Highland White Terrier", "American Cocker Spaniel", "English Bulldog", "Shih Tzu", "Lhasa Apso", "Pug", "Cavalier King Charles Spaniel", "Yorkshire Terrier"],
          "cat": ["Uncommon; usually after feline herpesvirus"]},
  home=["Clean discharge with a warm, damp cloth.", "Plain lubricating gel for comfort.", "Book a visit within a few days for a tear test."],
  dont=["Do not rely on antibiotic drops alone — they treat the infection, not the dryness.", "Avoid oral diphenhydramine (Benadryl): it reduces tear production.", "Do not stop tear-stimulating treatment once it works — it is lifelong."],
  hum=["Artificial tears", "Cyclosporine eye drops", "Cetirizine / loratadine"],
  dx=["Schirmer tear test (dogs: <15 mm/min suspicious, <10 KCS, <5 severe)", "Fluorescein stain", "Check for drug causes (sulfonamides such as trimethoprim-sulfa)", "Dry nostril on the same side suggests neurogenic KCS"],
  tx="Lacrimomimetic lifelong: cyclosporine 0.2% ointment q12h (FDA-approved for dogs); if STT does not rise after 6-8 weeks, tacrolimus 0.02-0.03% q12h. Tear replacement q4-6h. Topical antibiotic only for secondary infection. Neurogenic KCS: oral pilocarpine. Refractory: parotid duct transposition. Recheck STT at 4-6 weeks.",
  rx=[],
  spn={},
  rf=["Eye becomes painful, squinted, or cloudy", "Discharge with a visible spot on the cornea"],
  refs=[],
  see=["corneal-ulcer", "conjunctivitis", "cherry-eye"])

c(id="glaucoma", n="Glaucoma", sys="Eye", sp=["dog", "cat", "horse"],
  a=["high eye pressure", "IOP", "enlarged eye", "blue eye", "dilated pupil", "sudden blindness", "painful red eye"],
  tri="E", up="Acute glaucoma can blind the eye within 24-48 hours.",
  zoo=False, reg="",
  what="Pressure inside the eye rises because fluid cannot drain. In dogs it is often an inherited drainage-angle problem that later affects the other eye; in cats and horses it usually follows inflammation (uveitis).",
  signs=["Very red eye with large, visible blood vessels", "Cloudy or bluish cornea", "Pupil larger than the other side, slow to react to light", "Eye looks bigger", "Pain: squinting, head-shy, lethargy, poor appetite", "Sudden blindness or bumping into things"],
  breeds={"dog": ["American Cocker Spaniel", "Basset Hound", "Chow Chow", "Shar-Pei", "Boston Terrier", "Wire Fox Terrier", "Norwegian Elkhound", "Siberian Husky", "Cairn Terrier", "Miniature Poodle", "Shih Tzu (reported)"],
          "cat": ["Usually secondary to chronic uveitis or intraocular tumor"],
          "horse": ["Usually secondary to equine recurrent uveitis"]},
  home=["Go now — this is an emergency.", "Use a harness, not a neck collar (neck pressure raises eye pressure).", "Keep the animal calm and cool."],
  dont=["Do not give oral antihistamines (diphenhydramine) or atropine drops.", "Do not wait until morning.", "Do not start glaucoma drops from a family member's prescription before the pressure is measured."],
  hum=["Latanoprost", "Dorzolamide / dorzolamide-timolol", "Atropine 1%"],
  dx=["Tonometry in both eyes (dogs: typical normal ~10-25 mmHg; elevation with clinical signs supports glaucoma)", "Gonioscopy of the fellow eye", "Exclude anterior lens luxation and uveitis before prostaglandins", "Fundus and menace response for vision prognosis"],
  tx="Acute primary glaucoma (dog): latanoprost 0.005% if no uveitis or anterior lens luxation, dorzolamide ± timolol, IV mannitol if IOP remains high, analgesia, same-day ophthalmology referral. Start prophylaxis in the fellow eye — it is often affected within months. Blind, painful eye: enucleation or intrascleral prosthesis. Cats and horses: treat the uveitis; dorzolamide-timolol; prostaglandins are ineffective (cats) or not first-line (horses).",
  rx=["Gabapentin"],
  spn={"cat": "Feline glaucoma is usually secondary — look for uveitis, FeLV/FIV/FIP, lymphoma, or intraocular melanoma.",
       "horse": "Suspect in any horse with recurrent uveitis and a cloudy, enlarged eye."},
  rf=["Any of the signs above — glaucoma is always urgent"],
  refs=["Gelatt KN, MacKay EO. Prevalence of the breed-related glaucomas in pure-bred dogs in North America. Vet Ophthalmol. 2004;7(2):97-111. PMID 14982589"],
  see=["uveitis", "lens-luxation", "cataract"])

c(id="uveitis", n="Uveitis (inflammation inside the eye)", sys="Eye", sp=["dog", "cat", "horse"],
  a=["uveitis", "moon blindness", "ERU", "equine recurrent uveitis", "cloudy eye", "small pupil", "iris color change", "hyphema", "blood in eye"],
  tri="U", up="Emergency if the eye is blind, very painful, or has blood or pus inside.",
  zoo=False, reg="Texas: tick-borne diseases (Ehrlichia, Anaplasma, Rocky Mountain spotted fever) and systemic fungal infections are common causes in dogs.",
  what="Inflammation of the iris and the structures inside the eye. It is often a sign of disease elsewhere in the body — infection, immune disease, or cancer — and can lead to glaucoma and cataract.",
  signs=["Red, painful eye with squinting", "Pupil smaller than the other side", "Hazy or cloudy eye", "Iris changing color", "Blood or white material in the front of the eye", "Light sensitivity"],
  breeds={"dog": ["Golden Retriever (pigmentary uveitis)", "Any breed with tick exposure"],
          "cat": ["Any cat — test for FeLV, FIV, FIP, toxoplasmosis"],
          "horse": ["Appaloosa", "Warmbloods", "Leptospirosis-exposed horses"]},
  home=["Keep the animal indoors, out of bright light.", "See a vet within 24 hours."],
  dont=["No steroid drops before a fluorescein stain.", "Do not treat the eye alone — the cause is often elsewhere in the body."],
  hum=["Steroid or steroid-antibiotic eye drops", "Atropine 1%", "Dorzolamide / dorzolamide-timolol"],
  dx=["Tonometry (IOP often low; normal or high IOP with uveitis suggests secondary glaucoma)", "Fluorescein stain", "Aqueous flare, keratic precipitates, fundus exam", "Systemic work-up: CBC, chemistry, urinalysis, tick-borne panel (dog), FeLV/FIV/FIP/toxoplasma (cat), leptospirosis (horse), imaging"],
  tx="Topical corticosteroid (prednisolone acetate 1%) if fluorescein-negative, or topical NSAID; atropine if IOP is not elevated; systemic NSAID or corticosteroid; treat the underlying cause. Monitor IOP for secondary glaucoma. Horses (ERU): long-term management, fly mask, suprachoroidal cyclosporine implant by an ophthalmologist.",
  rx=["Meloxicam", "Flunixin meglumine"],
  spn={"horse": "Equine recurrent uveitis is the leading cause of blindness in horses. Any painful eye is an emergency.",
       "cat": "Always test for infectious and neoplastic causes."},
  rf=["Sudden blindness", "Blood or pus visible inside the eye", "Eye pain with fever, lethargy, or not eating"],
  refs=[],
  see=["glaucoma", "cataract", "corneal-ulcer"])

c(id="conjunctivitis", n="Conjunctivitis (allergic, bacterial, or irritant)", sys="Eye", sp=["dog", "cat", "rabbit"],
  a=["pink eye", "red eye", "eye discharge", "itchy eyes", "allergic conjunctivitis", "watery eyes", "eye infection"],
  tri="S", up="Within 24 hours if the animal squints, the cornea is cloudy, or only one eye is involved with pain.",
  zoo=False, reg="",
  what="Inflammation of the pink tissue around the eye. In dogs it is most often allergic or a sign of another eye problem; in cats it is usually viral (herpesvirus) or Chlamydia/Mycoplasma. A red eye should be called conjunctivitis only after dry eye, ulcer, uveitis, and glaucoma are ruled out.",
  signs=["Pink or red tissue around the eye", "Clear to mucus-like discharge", "Rubbing", "Both eyes affected (allergy) or one eye (irritant, foreign body)", "No squinting, normal clear cornea (mild cases)"],
  breeds={"dog": ["Atopic dogs: West Highland White Terrier, Labrador and Golden Retriever, French Bulldog, Boxer, Shih Tzu"],
          "cat": ["Kittens and shelter cats (infectious)"]},
  home=["Rinse with sterile saline 2-3 times daily.", "Trim hair near the eye.", "A 48-hour home trial is reasonable only if the eye is open, the cornea is clear, and the animal is comfortable."],
  dont=["No 'redness relief' drops (Visine, Clear Eyes).", "No steroid drops before a fluorescein stain.", "No skin ointments in the eye."],
  hum=["Artificial tears", "Antihistamine eye drops", "Cetirizine / loratadine", "Triple antibiotic eye ointment", "Redness-relief eye drops"],
  dx=[EXAM3, "Look under the third eyelid for foreign material", "Cats: consider FHV-1, Chlamydia felis, Mycoplasma PCR"],
  tx="Allergic (dog): control atopy; topical corticosteroid after a negative stain, or antihistamine / mast-cell stabilizer drops. Bacterial (usually secondary): topical broad-spectrum antibiotic; find the primary cause. Cats: FHV-1 — famciclovir; Chlamydia/Mycoplasma — oral doxycycline (follow each dose with water to prevent esophageal stricture).",
  rx=[],
  spn={"cat": "Herpesvirus is the most likely cause — see the FHV-1 card.",
       "rabbit": "Eye discharge in rabbits is often tear-duct infection linked to dental disease — see the epiphora card."},
  rf=["Squinting or eye held shut", "Cloudy cornea", "Kitten with eyes sealed shut", "No improvement in 48 hours"],
  refs=[],
  see=["kcs", "fhv1", "epiphora", "eyelid-hair"])

c(id="eyelid-hair", n="Eyelid and hair disorders (entropion, distichiasis, nasal-fold hair)", sys="Eye", sp=["dog", "cat"],
  a=["entropion", "distichiasis", "ectopic cilia", "trichiasis", "nasal fold", "hair in eye", "rolled eyelid", "eyelash"],
  tri="S", up="Within 24 hours if the eye is squinted or cloudy (secondary ulcer).",
  zoo=False, reg="",
  what="The eyelid rolls inward (entropion), extra eyelashes grow from the lid margin (distichiasis) or through its inner surface (ectopic cilia), or facial hair from the nasal fold rubs the eye. Constant rubbing causes tearing, pain, and ulcers that keep coming back.",
  signs=["Chronic tearing and tear staining", "Squinting", "Hair or lashes visibly touching the eye", "Recurring corneal ulcers", "Rubbing the face"],
  breeds={"dog": ["Shar-Pei", "Chow Chow", "English Bulldog", "Pug", "Shih Tzu", "Pekingese", "Lhasa Apso", "American Cocker Spaniel", "Poodle", "Rottweiler"],
          "cat": ["Persian", "Himalayan"]},
  home=["Keep hair around the eyes trimmed short (blunt-tipped scissors or a groomer).", "Plain lubricating gel for comfort.", "Book a visit — these problems are mechanical and do not respond to drops alone."],
  dont=["Do not pluck lashes at home.", "Do not expect antibiotic or allergy drops to fix it."],
  hum=["Artificial tears"],
  dx=["Magnified exam of the lid margins", "Fluorescein stain for secondary ulcers", "Eversion of the lid for ectopic cilia"],
  tx="Distichiasis/ectopic cilia: cryoepilation or electroepilation; ectopic cilia need surgical excision. Entropion: temporary tacking sutures in puppies, definitive correction (Hotz-Celsus) after maturity. Nasal-fold trichiasis and medial canthal entropion: fold resection or medial canthoplasty. Manual epilation is temporary (regrowth in weeks).",
  rx=[],
  spn={},
  rf=["Squinting with a cloudy spot on the eye"],
  refs=[],
  see=["corneal-ulcer", "epiphora"])

c(id="cherry-eye", n="Cherry eye (prolapsed third-eyelid gland)", sys="Eye", sp=["dog", "cat"],
  a=["cherry eye", "third eyelid", "nictitans gland prolapse", "red lump corner of eye"],
  tri="S", up="",
  zoo=False, reg="",
  what="The tear gland of the third eyelid pops out and appears as a red, cherry-like lump in the inner corner of the eye. It is not painful at first, but the gland produces a large share of the tears and must be preserved.",
  signs=["Smooth red lump at the inner corner of the eye", "Usually in dogs under 2 years", "Mild discharge"],
  breeds={"dog": ["English Bulldog", "French Bulldog", "Beagle", "American Cocker Spaniel", "Neapolitan Mastiff", "Shih Tzu", "Lhasa Apso"],
          "cat": ["Burmese (rare)"]},
  home=["Keep the area clean and moist with lubricating gel.", "Prevent rubbing.", "Book a visit."],
  dont=["Do not agree to removal of the gland — removal leads to dry eye later. Replacement surgery is the standard."],
  hum=["Artificial tears"],
  dx=["Exam; Schirmer tear test before surgery"],
  tx="Surgical replacement (pocket technique or anchoring). Excision is contraindicated because it predisposes to KCS. Recurrence is possible and may need a second procedure.",
  rx=[],
  spn={},
  rf=["Lump becomes dark, dry, or bleeding", "Squinting or cloudy eye"],
  refs=[],
  see=["kcs"])

c(id="fhv1", n="Feline herpesvirus (FHV-1) eye disease", sys="Eye", sp=["cat"],
  a=["feline herpes", "FHV", "FHV-1", "cat flu", "cat conjunctivitis", "kitten eye infection", "cat sneezing", "dendritic ulcer", "herpes"],
  tri="S", up="Within 24 hours for kittens, eyes sealed shut, a cloudy cornea, or a cat that stops eating.",
  zoo=False, reg="",
  what="Most cats carry herpesvirus for life after infection. Stress, illness, or steroid use can reactivate it, causing conjunctivitis, corneal ulcers, and sneezing. It does not infect people or dogs.",
  signs=["Squinting and tearing, often one eye first", "Red, swollen conjunctiva", "Sneezing and nasal discharge", "Flare-ups after stress (boarding, a move, a new pet)", "Kittens: eyes crusted or sealed shut"],
  breeds={"cat": ["Kittens", "Shelter and multi-cat households", "Brachycephalic breeds (Persian, Himalayan)"]},
  home=["Wipe discharge with warm water.", "Keep the cat eating — warm up wet food to strengthen smell.", "Reduce stress; separate from other cats if a flare-up starts."],
  dont=["Skip lysine — controlled evidence shows it does not work.", "No steroid eye drops.", "No triple antibiotic eye ointment without a vet (rare anaphylaxis in cats)."],
  hum=["Famciclovir", "L-lysine", "Triple antibiotic eye ointment", "Fluoroquinolone eye drops", "Artificial tears"],
  dx=["Clinical diagnosis in most cases", "Fluorescein stain (branching dendritic ulcers are characteristic)", "PCR can be positive in healthy carriers — interpret with signs"],
  tx="Famciclovir 90 mg/kg PO q12h until about 1 week after signs resolve; topical antivirals (cidofovir 0.5% q12h, idoxuridine, trifluridine — the last two sting) as alternatives or adjuncts; topical antibiotic for secondary infection; avoid corticosteroids. Core vaccination reduces severity but does not prevent infection.",
  rx=[],
  spn={},
  rf=["Kitten with sealed eyes or not eating", "Cloudy cornea or a dark plaque on the cornea", "Cat not eating for more than 24 hours"],
  refs=["Thomasy SM, Shull O, Outerbridge CA, et al. Oral administration of famciclovir for treatment of spontaneous ocular, respiratory, or dermatologic disease attributed to feline herpesvirus type 1: 59 cases (2006-2013). J Am Vet Med Assoc. 2016;249(5):526-538. PMID 27556267",
        "Sebbag L, Thomasy SM, Woodward AP, et al. Pharmacokinetic modeling of penciclovir and BRL42359 in the plasma and tears of healthy cats to optimize dosage recommendations for oral administration of famciclovir. Am J Vet Res. 2016;77(8):833-845. PMID 27463546",
        "Bol S, Bunnik EM. Lysine supplementation is not effective for the prevention or treatment of feline herpesvirus 1 infection in cats: a systematic review. BMC Vet Res. 2015;11:284. PMID 26573523"],
  see=["conjunctivitis", "corneal-ulcer"])

c(id="cataract", n="Cataract vs. nuclear sclerosis (cloudy lens)", sys="Eye", sp=["dog", "cat"],
  a=["cataract", "nuclear sclerosis", "lenticular sclerosis", "cloudy eye old dog", "blue eyes aging", "white pupil", "diabetic cataract"],
  tri="S", up="Within 24 hours if the eye turns red or painful (lens-induced uveitis), or in a diabetic dog whose vision is changing fast.",
  zoo=False, reg="",
  what="Nuclear sclerosis is a normal bluish-grey haze of the lens in dogs from about middle age; vision is barely affected. A cataract is a true white opacity that blocks vision and can inflame the eye. Diabetic dogs very often develop cataracts, sometimes within weeks.",
  signs=["Grey-blue haze in both pupils (nuclear sclerosis)", "White or crushed-ice look in the pupil (cataract)", "Bumping into things, reluctance in dim light", "Increased thirst and urination (diabetes)"],
  breeds={"dog": ["Miniature Poodle", "American Cocker Spaniel", "Bichon Frise", "Boston Terrier", "Labrador Retriever", "Siberian Husky", "Yorkshire Terrier", "Any diabetic dog"],
          "cat": ["Usually secondary to uveitis"]},
  home=["Keep furniture in place; use scent or sound cues for a vision-impaired pet.", "Book a visit for a lens exam and a blood glucose check."],
  dont=["Do not buy drops marketed to 'dissolve' cataracts — there is no proof they work.", "Do not delay if a diabetic dog's eyes suddenly cloud."],
  hum=[],
  dx=["Retroillumination: fundus reflex is visible through nuclear sclerosis and blocked by cataract", "IOP and flare (lens-induced uveitis)", "Blood glucose and urinalysis", "Pre-surgical ocular ultrasound and electroretinography"],
  tx="Nuclear sclerosis: none. Cataract: phacoemulsification by a veterinary ophthalmologist; topical NSAID or corticosteroid to control lens-induced uveitis whether or not surgery is chosen. Regulate diabetes first.",
  rx=["Insulin (veterinary)"],
  spn={},
  rf=["Red, painful eye with a cloudy lens", "Sudden vision loss"],
  refs=[],
  see=["uveitis", "glaucoma", "lens-luxation"])

c(id="proptosis", n="Proptosis (eye out of the socket)", sys="Eye", sp=["dog", "cat"],
  a=["proptosis", "eye popped out", "eye out of socket", "bulging eye", "trauma eye"],
  tri="E", up="",
  zoo=False, reg="",
  what="The eyeball is pushed forward in front of the eyelids, usually after trauma. Flat-faced dogs can proptose with minor pressure; in cats and long-nosed dogs it takes major trauma and the outlook is worse.",
  signs=["Eyeball sitting in front of the eyelids", "Eyelids unable to close over it", "Bleeding, bruising, or a head injury"],
  breeds={"dog": ["Pug", "Shih Tzu", "Pekingese", "Boston Terrier", "French Bulldog", "Chihuahua"]},
  home=["Go now.", "Keep the eye wet: cover it with a clean cloth soaked in saline or lubricating gel.", "Prevent pawing; use a cone if available.", "Carry the pet — avoid neck pressure."],
  dont=["Do not try to push the eye back in.", "Do not let the eye dry out."],
  hum=["Artificial tears"],
  dx=["Pupillary light reflexes (direct and consensual)", "Globe integrity; number of avulsed extraocular muscles", "Skull and orbital fractures; systemic trauma survey"],
  tx="Replacement under general anesthesia with temporary tarsorrhaphy, systemic anti-inflammatory and antibiotic therapy. Enucleation for a ruptured globe or major muscle avulsion. Favorable: brachycephalic dog, positive PLR, vision at presentation. Unfavorable: cats, non-brachycephalic dogs, hyphema, no visible pupil, fractures, three or more avulsed muscles.",
  rx=["Meloxicam", "Amoxicillin / amoxicillin-clavulanate"],
  spn={},
  rf=["Always an emergency"],
  refs=["Gilger BC, Hamilton HL, Wilkie DA, van der Woerdt A, McLaughlin SA, Whitley RD. Traumatic ocular proptoses in dogs and cats: 84 cases (1980-1993). J Am Vet Med Assoc. 1995;206(8):1186-1190. PMID 7768741"],
  see=["corneal-ulcer"])

c(id="lens-luxation", n="Lens luxation", sys="Eye", sp=["dog", "cat"],
  a=["lens luxation", "dislocated lens", "terrier eye", "ADAMTS17", "wobbly iris"],
  tri="E", up="Anterior luxation causes acute glaucoma.",
  zoo=False, reg="",
  what="The lens slips out of its normal position. In certain terriers it is inherited and often affects both eyes; a lens that falls forward blocks drainage and causes painful glaucoma within hours.",
  signs=["Sudden red, painful, cloudy eye", "Edge of the lens visible as a crescent in the pupil", "Trembling iris when the eye moves"],
  breeds={"dog": ["Jack Russell and Parson Russell Terrier", "Fox Terriers", "Miniature Bull Terrier", "Tibetan Terrier", "Sealyham Terrier", "Border Collie", "Chinese Crested", "Shar-Pei"],
          "cat": ["Older cats with chronic uveitis (often well tolerated)"]},
  home=["Go now.", "Keep calm, harness instead of collar."],
  dont=["No atropine or dilating drops at home.", "Do not start latanoprost before an exam — it is contraindicated with an anterior lens."],
  hum=["Latanoprost", "Dorzolamide / dorzolamide-timolol"],
  dx=["Slit-lamp exam; IOP", "Fellow eye exam", "DNA test for the ADAMTS17 primary lens luxation mutation in predisposed breeds"],
  tx="Anterior luxation in dogs: emergency lens extraction by an ophthalmologist; control IOP meanwhile. Posterior or subluxated lens: topical miotic to keep the lens behind the iris, monitor IOP. Test breeding stock.",
  rx=[],
  spn={"cat": "Cats often tolerate anterior luxation better than dogs; still needs IOP monitoring."},
  rf=["Always urgent — sudden painful eye in a predisposed terrier is lens luxation until proven otherwise"],
  refs=[],
  see=["glaucoma", "cataract", "uveitis"])

c(id="epiphora", n="Tearing and tear staining (epiphora, blocked tear duct)", sys="Eye", sp=["dog", "cat", "rabbit"],
  a=["epiphora", "tear staining", "watery eye", "constant tearing", "tear duct", "nasolacrimal", "dacryocystitis", "brown stains under eyes", "excessive tearing"],
  tri="H", up="Book a visit if tearing lasts more than a few days; within 24 hours if there is squinting, redness, or cloudiness.",
  zoo=False, reg="",
  what="Tears overflow either because the eye is making extra tears (something is irritating it) or because the tear duct cannot drain them. Constant tearing is a symptom — the cause is what matters.",
  signs=["Wet fur and reddish-brown staining below the inner corner of the eye", "Clear watery discharge", "Odor or yeast in the stained fur"],
  breeds={"dog": ["Shih Tzu", "Maltese", "Poodle", "Bichon Frise", "Lhasa Apso", "Pug"],
          "cat": ["Persian", "Himalayan"],
          "rabbit": ["Lop-eared and dwarf breeds (dental root disease)"]},
  home=["Wipe the area twice daily with saline and keep it dry.", "Trim hair around the eyes.", "Check for squinting, redness, or cloudiness — if present, see the corneal ulcer, glaucoma, and eyelid cards."],
  dont=["Avoid 'tear stain' supplements or powders that contain antibiotics — some have been sold without FDA approval.", "No redness-relief drops."],
  hum=["Artificial tears", "Antihistamine eye drops"],
  dx=[EXAM3, "Fluorescein passage test (dye appearing at the nostril indicates a patent duct; false negatives are common in flat-faced breeds)", "Nasolacrimal flush", "Rabbits: skull radiographs or CT for dental disease"],
  tx="Remove the cause: eyelid/hair surgery, allergy control, ulcer or glaucoma treatment. Blocked duct: flush, cannulation; imperforate punctum: surgical opening. Brachycephalic medial canthal entropion: medial canthoplasty. Rabbits: treat dental disease and dacryocystitis (repeated flushing with appropriate antibiotics).",
  rx=[],
  spn={"rabbit": "White discharge from the inner corner is typically dacryocystitis tied to overgrown tooth roots — needs a dental work-up."},
  rf=["Squinting, cloudy cornea, or one eye suddenly worse", "Thick pus from the inner corner"],
  refs=[],
  see=["eyelid-hair", "conjunctivitis", "corneal-ulcer", "glaucoma"])
